import Link from "next/link";
import AppNav from "@/components/layout/app-nav";
import { getRecruiterOrAdmin } from "@/lib/auth/server";
import { listInterviewRequests } from "@/lib/db/interview-requests";

export default async function InterviewRequestsPage() {
  const access = await getRecruiterOrAdmin();
  if (access.status !== 200) return <><AppNav /><main className="mx-auto max-w-3xl px-5 py-20 sm:px-8"><h1 className="text-4xl font-semibold tracking-[-.07em]">Interview requests</h1><p className="mt-5 text-sm text-[#777772]">This administrative view is available to recruiters and admins only.</p></main></>;
  const requests = await listInterviewRequests();
  return <><AppNav /><main className="mx-auto w-full max-w-7xl px-5 py-12 sm:px-8 lg:py-16"><div className="flex flex-col justify-between gap-5 border-b border-[#deded9] pb-8 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#f48120]">Operations / Requests</p><h1 className="mt-4 text-5xl font-semibold tracking-[-.08em]">Interview requests.</h1></div><p className="max-w-sm text-sm leading-6 text-[#777772]">Requests arrive from the Recruitment Portal. Scheduling and candidate slot selection are reserved for a later phase.</p></div><div className="mt-8 overflow-x-auto border border-[#deded9] bg-white"><table className="w-full min-w-[720px] text-left"><thead className="border-b border-[#deded9] bg-[#fafaf8] text-[10px] uppercase tracking-[.16em] text-[#9b9b96]"><tr><th className="px-5 py-4 font-semibold">Candidate</th><th className="px-5 py-4 font-semibold">Position</th><th className="px-5 py-4 font-semibold">Round</th><th className="px-5 py-4 font-semibold">Duration</th><th className="px-5 py-4 font-semibold">Status</th><th className="px-5 py-4 font-semibold">Created</th></tr></thead><tbody className="divide-y divide-[#deded9]">{requests.map((request) => <tr key={request.id} className="text-sm"><td className="px-5 py-5"><Link href={`/interview-requests/${request.id}`} className="font-semibold hover:text-[#f48120]">{request.candidateName}</Link><p className="mt-1 text-xs text-[#8a8a85]">{request.candidateEmail}</p></td><td className="px-5 py-5 text-[#555550]">{request.jobTitle}</td><td className="px-5 py-5 text-[#555550]">{request.roundName}</td><td className="px-5 py-5 text-[#555550]">{request.durationMinutes} min</td><td className="px-5 py-5"><span className={`inline-flex px-2 py-1 text-[10px] font-semibold uppercase tracking-wider ${request.status === "OPEN" ? "bg-[#eff7ee] text-[#486d46]" : "bg-[#fff0e2] text-[#8a6038]"}`}>{request.status}</span></td><td className="px-5 py-5 text-xs text-[#8a8a85]">{new Date(request.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</td></tr>)}{requests.length === 0 && <tr><td colSpan={6} className="px-5 py-16 text-center text-sm text-[#8a8a85]">No interview requests yet.</td></tr>}</tbody></table></div></main></>;
}
